version: '2'
services:
  microserviceboilerplate-mongodb:
    image: mongo:4.2.7
    ports:
      - '27017:27017'
    # volumes:
    #     - ~/volumes/jhipster/microserviceBoilerplate/mongodb/:/data/db/
